name: 🚀 Deploy React App to WordPress via FTP

on:
  push:
    branches:
      - master # or 'master' or any branch you want to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧱 Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🔨 Build App
        run: npm run build

      - name: 🚀 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist # or ./build if using CRA
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
